#!/usr/bin/env python3
"""
Render the Projects cards in index.html from tools/projects/projects.json.

The cards stay as real markup in index.html (rather than being built by JS at
runtime) so they remain crawlable and work without scripts. Re-run after editing
projects.json:

    python3 tools/projects/build_cards.py

Use --check to verify index.html is already up to date without writing.
"""
import argparse
import html
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
INDEX = ROOT / "index.html"
DATA = ROOT / "tools" / "projects" / "projects.json"

START = "        <!-- projects:start (generated by tools/projects/build_cards.py) -->"
END = "        <!-- projects:end -->"

DEFAULT_IMAGE = "assets/images/projects/placeholder-{n:02d}.svg"

CARD = """        <div class="work__cell" data-title="{title}" data-stack="{stack}">
          <a class="card project-card" href="{url}" target="_blank" rel="noopener" data-project-card>
            <div class="project-card__visual">
              <img class="project-card__image" src="{image}" alt="{aria}" loading="lazy" decoding="async" width="880" height="1100" />
            </div>
            <div class="project-card__top">
              <span class="project-card__tag">{stack}</span>
              <span class="project-card__number" aria-hidden="true">{number:02d}</span>
            </div>
            <div class="project-card__info">
              <div>
                <h3>{title}</h3>
                <p>{blurb}</p>
              </div>
              <span class="project-card__arrow" aria-hidden="true">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M7 17 17 7M8 7h9v9"/></svg>
              </span>
            </div>
            <span class="sr-only">{sr}</span>
          </a>
        </div>
"""


def render(projects):
    out = [START]
    for i, p in enumerate(projects, start=1):
        image = p.get("image") or DEFAULT_IMAGE.format(n=i)
        if not (ROOT / image).exists():
            sys.exit(f"error: {p['repo']} image not found: {image}")
        url = p.get("url") or f"https://github.com/BYTEJAYS/{p['repo']}"
        sr = ("Open the live site in a new tab" if p.get("url")
              else "Open repository in a new tab")
        out.append(CARD.format(
            url=html.escape(url, quote=True),
            image=html.escape(image, quote=True),
            aria=html.escape(p["aria"], quote=True),
            stack=html.escape(p["stack"]),
            number=i,
            title=html.escape(p["title"]),
            blurb=html.escape(p["blurb"]),
            sr=sr,
        ).rstrip("\n"))
    out.append(END)
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if index.html is out of date")
    args = ap.parse_args()

    projects = json.loads(DATA.read_text())["projects"]
    block = render(projects)
    source = INDEX.read_text()

    if START not in source or END not in source:
        sys.exit("error: projects markers not found in index.html; add\n"
                 f"{START}\n{END}\ninside the .work__grid element")

    head, _, rest = source.partition(START)
    _, _, tail = rest.partition(END)
    updated = head + block.rstrip("\n") + tail

    if args.check:
        if updated != source:
            sys.exit("index.html is out of date - run tools/projects/build_cards.py")
        print(f"up to date ({len(projects)} projects)")
        return

    if updated == source:
        print(f"no change ({len(projects)} projects)")
        return

    INDEX.write_text(updated)
    print(f"wrote {len(projects)} project cards into {INDEX.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
